version: "3.7"

volumes:
  mongo_data: {}
  nginx-internal-conf: {}
  nginx-internal-html: {}
  nginx-internal-certs: {}

services:
  mongo:
    image: mongo:4.2.3
    restart: always
    container_name: mongo
    volumes:
      - mongo_data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodbROOT
      - MONGO_INITDB_DATABASE=factor

  factor:
    build:
      context: ..
    image: app
    container_name: app
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - .:/var/factor
      - /var/factor/node_modules/
    environment:
      VIRTUAL_HOST: white-wall.dev
      LETSENCRYPT_HOST: white-wall.dev
      FACTOR_ADMINS: sebastian@white-wall.dev
      DB_CONNECTION: mongodb+srv://factor:factor@mongo/factor?retryWrites=true&w=majority
      FACTOR_URL: https://white-wall.dev

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-internal-conf:/etc/nginx/conf.d:ro
      - nginx-internal-html:/usr/share/nginx/html:ro
      - nginx-internal-certs:/etc/nginx/certs:ro

  proxy:
    restart: always
    image: jwilder/docker-gen
    container_name: proxy
    environment:
      - ENABLE_IPV6=true
    volumes:
      - nginx-internal-conf:/etc/nginx/conf.d
      - nginx-internal-certs:/etc/nginx/certs
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen.=true
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - nginx-internal-conf:/etc/nginx/conf.d
      - nginx-internal-html:/usr/share/nginx/html
      - nginx-internal-certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
